################################################################################
#               HACKATHON PARTICIPANTS -- DO NOT EDIT THIS FILE                #
################################################################################

################################################################################
# source scripts - need this to prep data and have access to the predict methods
source("prepare_mortality_data.R")
source("prepare_fss_data.R")
source("mortality_model.R")
source("fss_model.R")

VERSION <- commandArgs(trailingOnly = TRUE)[1]
USE_TESTING_DATA <- file.exists("./csvs/testing.csv")

################################################################################
# import the trained models
trained_mortality_model <- readRDS(file = "./output/trained_mortality_model.rds")
trained_fss_model       <- readRDS(file = "./output/trained_fss_model.rds")

################################################################################
# import and prepare the training data set
tic <- Sys.time()
m_training_data <- prepare_mortality_data(training = TRUE)
toc <- Sys.time()

cat("seconds elapsed to prepare mortality training data |",
    as.numeric(difftime(toc, tic, units = "secs")),
    "\n",
    file = "./output/evaluation.txt",
    sep = " ",
    append = TRUE)

tic <- Sys.time()
f_training_data <- prepare_fss_data(training = TRUE)
toc <- Sys.time()

cat("seconds elapsed to prepare fss training data |",
    as.numeric(difftime(toc, tic, units = "secs")),
    "\n",
    file = "./output/evaluation.txt",
    sep = " ",
    append = TRUE)

################################################################################
# prediction for the mortality outcome

tic <- Sys.time()
predicted_mortality <- predict(trained_mortality_model, newdata = m_training_data)
write.table(predicted_mortality,
            file = "./output/predicted_mortality_training.dat",
            quote = FALSE,
            row.names = FALSE,
            col.names = FALSE)
toc <- Sys.time()

cat("seconds elapsed to predict mortality on training data |",
    as.numeric(difftime(toc, tic, units = "secs")),
    "\n",
    file = "./output/evaluation.txt",
    sep = " ",
    append = TRUE)

################################################################################
# prediction for the fss total
tic <- Sys.time()
predicted_fss <- predict(trained_fss_model, newdata = f_training_data)
write.table(predicted_fss,
            file = "./output/predicted_fss_training.dat",
            quote = FALSE,
            row.names = FALSE,
            col.names = FALSE)
toc <- Sys.time()

cat("seconds elapsed to predict FSS on training data |",
    as.numeric(difftime(toc, tic, units = "secs")),
    "\n",
    file = "./output/evaluation.txt",
    sep = " ",
    append = TRUE)


################################################################################
################################################################################

if (USE_TESTING_DATA) {

  ################################################################################
  # import and prepare the testing (holdout) data set
  tic <- Sys.time()
  m_testing_data <- prepare_mortality_data(training = FALSE)
  toc <- Sys.time()

  cat("seconds elapsed to prepare mortality testing data |",
      as.numeric(difftime(toc, tic, units = "secs")),
      "\n",
      file = "./output/evaluation.txt",
      sep = " ",
      append = TRUE)

  tic <- Sys.time()
  f_testing_data <- prepare_fss_data(training = FALSE)
  toc <- Sys.time()

  cat("seconds elapsed to prepare fss testing data |",
      as.numeric(difftime(toc, tic, units = "secs")),
      "\n",
      file = "./output/evaluation.txt",
      sep = " ",
      append = TRUE)

  ################################################################################
  # prediction for the mortality outcome

  tic <- Sys.time()
  predicted_mortality <- predict(trained_mortality_model, newdata = m_testing_data)
  write.table(predicted_mortality,
              file = "./output/predicted_mortality_testing.dat",
              quote = FALSE,
              row.names = FALSE,
              col.names = FALSE)
  toc <- Sys.time()

  cat("seconds elapsed to predict mortality on testing data |",
      as.numeric(difftime(toc, tic, units = "secs")),
      "\n",
      file = "./output/evaluation.txt",
      sep = " ",
      append = TRUE)

  ################################################################################
  # prediction for the fss total
  tic <- Sys.time()
  predicted_fss <- predict(trained_fss_model, newdata = f_testing_data)
  write.table(predicted_fss,
              file = "./output/predicted_fss_testing.dat",
              quote = FALSE,
              row.names = FALSE,
              col.names = FALSE)
  toc <- Sys.time()

  cat("seconds elapsed to predict FSS on testing data |",
      as.numeric(difftime(toc, tic, units = "secs")),
      "\n",
      file = "./output/evaluation.txt",
      sep = " ",
      append = TRUE)

}

################################################################################
#                                 End of File                                  #
################################################################################
