################################################################################
#               HACKATHON PARTICIPANTS -- DO NOT EDIT THIS FILE                #
################################################################################

response <- commandArgs(trailingOnly = TRUE)[1]

source(paste0("prepare_", response, "_data.R"))
source(paste0(response, "_model.R"))

################################################################################
# build the training data set and record the time required to do so.

tic <- Sys.time()

training_data <- do.call(paste0("prepare_", response, "_data"), list(training = TRUE))

toc <- Sys.time()

cat("seconds elapsed to prepare",
    response,
    "training data |",
    as.numeric(difftime(toc, tic, units = "secs")),
    "\n",
    file = "./output/evaluation.txt",
    sep = " ",
    append = TRUE)

################################################################################
# Train the model and record the time required to do so.

tic <- Sys.time()

trained_model <- do.call(paste0(response, "_model"), list(data = training_data))

toc <- Sys.time()

saveRDS(trained_model, file = paste0("./output/trained_", response, "_model.rds"))

cat("seconds elapsed to train the",
    response,
    "model |",
    as.numeric(difftime(toc, tic, units = "secs")),
    "\n",
    file = "./output/evaluation.txt",
    sep = " ",
    append = TRUE)

################################################################################
#                                 End of File                                  #
################################################################################

